/* Wurzeln von a+i b: */

display2d : false;

sgn(x) := if x>=0 then 1 else -1;

p(a,b) := sqrt(1/2*(a + sqrt(a^2 + b^2)));
q(a,b) := sgn(b) * sqrt(1/2*(-a + sqrt(a^2 + b^2)));
/* Anmerkungen fuer b=0:
   p(a,0) = if a>=0 then sqrt(a) else 0
   q(a,0) = if a>=0 then 0 else sqrt(-a)
*/

/* Die beiden Wurzeln: */
w1(a,b) := p(a,b) + %i * q(a,b);
w2(a,b) := -w1(a,b);

/*

Anschauen von Wurzeln:

plot2d([p(a,0), q(a,0)], [a,-10,10]);
plot2d([p(a,1), q(a,1)], [a,-10,10]);
plot2d([p(a,-1), q(a,-1)], [a,-10,10]);

Testen auf Null:

plot3d(realpart(w1(a,b)^2) - a, [a,-100,100], [b,-100,100]);
plot3d(imagpart(w1(a,b)^2) - b, [a,-100,100], [b,-100,100]);

plot3d(realpart(w2(a,b)^2) - a, [a,-100,100], [b,-100,100]);
plot3d(imagpart(w2(a,b)^2) - b, [a,-100,100], [b,-100,100]);

Die Fehlermeldungen "atan2: atan2(0,0) is undefined." kommen von der
numerischen Auswertung. Nicht bekannt, wie dies vermieden werden
kann.

*/
